### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ritashugisha** [ritashugisha/ASUEvents#1]
The following is a list of improvements that need to be completed before our presentation date.
This improvements on this list are not static.

- #### Important
    - [x] Full model integration in the **events** app
    - [ ] Separate views for individual rooms, buildings, events, and managers
    - [x] Sign up and Sign in authentication options for managers
    - [x] Tie sign up forms for managers with the default user form
    - [ ] Calendar portlet generation for the currently viewed object (room, event, ...etc)
    - [x] Generate dashboard view for index (include sign in and sign up options)
    - [ ] Manager event **manage** form
    - [ ] Implement event repetition calculations in calendars and event views
    - [ ] Fix search engine to search events title (white space inclusive)
    - [ ] Add in database buildings and rooms
    - [ ] Deploy site to *student.cs.appstate.edu*

- #### Research
    - [ ] Figure out how we may be able to tell an event to happen on multiple (separate) days per week

**Comment by ritashugisha** [comment]
Updated the todo list due to an advanced due date. Hopefully we can finish these features in time.
